'use client';
import { useRef,useState } from 'react'; import type { FiberBrowserNode } from '@fiber-pay/sdk/browser'; import { prepareChannel,startFiber } from '../lib/fiber'; import { createHoldInvoice,payHoldInvoice } from '../lib/hold';
export default function Page(){const sender=useRef<FiberBrowserNode|null>(null),receiver=useRef<FiberBrowserNode|null>(null);const[status,setStatus]=useState('Start both nodes');const[invoice,setInvoice]=useState('');const[pasted,setPasted]=useState('');const[hash,setHash]=useState<`0x${string}`|''>('');const[preimage,setPreimage]=useState<`0x${string}`|''>('');
async function start(role:'sender'|'receiver'){const node=await startFiber(`hold-${role}-v1`);if(role==='sender')sender.current=node;else receiver.current=node;setStatus(`${role} running`)}
async function prepare(role:'sender'|'receiver'){const node=role==='sender'?sender.current:receiver.current;if(!node)return;setStatus(`${role} connecting/opening`);await prepareChannel(node);setStatus('Wait for both channels to become CHANNEL_READY')}
async function create(){if(!receiver.current)return;const result=await createHoldInvoice(receiver.current,'1');setInvoice(result.invoice_address);setHash(result.payment_hash);setPreimage(result.preimage);await navigator.clipboard.writeText(result.invoice_address);setStatus('Hold Invoice copied')}
async function pay(){if(!sender.current)return;const result=await payHoldInvoice(sender.current,pasted);setStatus(`Payment ${result.status}; wait for receiver Received`)}
async function settle(){if(!receiver.current||!hash||!preimage)return;await receiver.current.settleInvoice({payment_hash:hash,payment_preimage:preimage});setStatus('Settled')}
async function cancel(){if(!receiver.current||!hash)return;await receiver.current.cancelInvoice({payment_hash:hash});setStatus('Cancelled')}
return <main><h1>Hold Invoice</h1><p className="status">{status}</p><div className="grid">{(['sender','receiver'] as const).map(role=><section className="card" key={role}><h2>{role}</h2><div className="row"><button onClick={()=>void start(role)}>Start</button><button onClick={()=>void prepare(role)}>Connect & open</button></div></section>)}</div><section className="card"><button onClick={()=>void create()}>Create Invoice and copy</button><textarea readOnly value={invoice}/></section><section className="card"><textarea onChange={e=>setPasted(e.target.value)} placeholder="Paste Invoice" value={pasted}/><div className="row"><button onClick={()=>void pay()}>Pay</button><button onClick={()=>void settle()}>Settle</button><button onClick={()=>void cancel()}>Cancel</button></div></section></main>}
